export const CLIENTS = [
  'Rodrigues e Almeida',
  'Rodrigues e Marreiros',
  'Nataliya Veselska',
  'Florometal',
  'Alumitex',
  'Albuperfil',
  'D.D.A',
  'JPO',
  'Silvestre e Sousa',
  'FVL',
  'Ribeiro e Rocha',
  'Francometal',
  'Cliente1',
  'Cliente2',
  'Cliente3',
  'Cliente4',
  'Cliente5',
  'Cliente6',
  'Cliente7',
  'Cliente8',
  'Cliente9',
  'Cliente10',
];
