export const CLIENTS = [
  'Brasio Inverno Unipessoal,  LDA',
  'Bruno Rodrigues',
  'Carlos Silva & Silva, LDA',
  'Alumicom,  LDA',
  'Duarte e Valério, LDA',
  'Carlos Manuel Domingos Teotónio, LDA',
  'Rodrigues & Almeida, LDA',
  'Triumph',
  'JPO - Sistemas em Caixilharia de Alumínios, LDA',
  'Élio Martins dos Santos - Alumínios, LDA',
  'ALUPR Alumínios e Vidros, LDA',
  'Carpintaria Irmãos Alves, LDA',
  'Vidrossonoba - Unipessoal, LDA',
  'Fernando Alegre, LDA',
  'Pedro Carlos Correia Leal',
  'Caixigarve, Unipessoal, LDA',
  'Fernando Henrique Quintal de Jesus, Herdeiros',
  'Nelson Silva Figueiredo',
  'Serralharia Brizimetal, LDA',
  'Justiniano Narciso P.Trindade',
  'Norberto Sequeira Unipessoal Limitada',
  'João Expedito',
  'Helder Manuel - Caixilharias, Unipessoal, LDA',
  'Manuel Torres',
  'Nuno Basso Alumínios LDA',
  'João Costa e António Tomé Jesus',
  'Roberto Marcos Unipessoal, LDA',
  'Bancada Superior Unipessoal, LDA',
  'Caixipronto, LDA',
  'Frame Addict, LDA',
  'Pradaria Decimal - Unipessoal, LDA',
  'Comev Construções Metalúrgicas de Viseu, LDA',
  'Profincom PVC, LDA',
  'Tagus PVC Caixilharia em PVC, LDA',
  'A Sovidro',
  'Jofica - Caixilharia, LDA',
  'F.J. Alumínios, LDA',
  'Ilidio Carrega',
  'Soblik Soluções, LDA',
  'Nelson Isidoro Rosa Martins',
  'Benepvc Fábrico e comércio de PVC, LDA',
  'Pais Industrias, LDA',
  'Alucalc - Lopes Rocha & Martins Pereira, LDA',
  'Alexandre Miguel Inácio Ribeiro',
  'Dário Honório - Caixilharias para arquitectura, LDA',
  'F V L - Indústria de caixilharia, LDA',
  'Caixideal, Serralharia civil, LDA',
  'Manuel Mata Fabrico e Mont. de Alumínios Unipessal, LDA',
  'Lusocaixilho, LDA',
  'Alberto Torres martinho Unipessoal, LDA',
  'Luminix LG - Caixilharias de Alumínios e PVC Unipessoal, LDA',
  'Armando Francisco Monteiro Pereira',
  'Paulo Jorge Gonçalves Silva Unipessoal, LDA',
  'Unividro, LDA',
  'Miguel Alexandre de Sousa Nascimento',
  'Paulo Pereira & Pereira - Alumínios, LDA',
  'Metalobernardo - transformação de Metais, LDA',
  'Prestigial Alumínios, LDA',
  'Allforalum - Alutech Solutions, LDA',
  'Pedro & Rui Alumínios, LDA',
  'Caixilagos - Caixilharia de Alumínios, LDA',
  'D.D.A. Serralharia Civil, LDA',
  'NA - NorteAlumínio Unipessoal, LDA',
  'Sytalmad Unipessoal, LDA',
  'Fernando Martins Carvalho e Irmãos Sá',
  'Irmãos Pinto Madureira - Caixilharia em Alumínio, LDA',
  'ACWIN, S.A.',
  'Irial Alumínios e Decorações Iriense, LDA',
  'Terraços Amistosos, LDA',
  'Leal & Lourenço - Carpintaria, LDA',
  'Jorge Manuel dos Reis - Caixilharia de Alumínio se PVC, LDA',
  'Vidrosegur - Unipessoal, LDA',
  'Jorge Manuel da Costa Coelho',
  'Diagonal Oportuna, LDA',
  'Rodrigues & Marreiros, LDA',
  'Tempo Astuto, Unipessoal',
  'Alumitex - Caixilharia de Alumínios e Ferro, LDA',
  'Ruben Bexiga Alumínios, LDA',
  'Caixilharia de Alumínios Irmãos Sabóia, LDA',
  'Carlos Eduardo dos Santos Florencio',
  'Mundeximio Unipessoal, LDA',
  'Serralharia Firmino & Firmino, LDA',
  'Hip Houzz EU, LDA',
  'Osvaldo Santos & Santos, LDA',
  'Agostinho & João Pinto, LDA',
  'Vetrometal, LDA',
  'Ribeiro e Rocha',
  'Suldernus - Soluções de Engenharia, LDA',
  'Prestigial Alumínios, LDA',
  'Albuperfil, LDA',
  'Nataliya Veselska',
  'Florometal, LDA',
  'Silvestre e Sousa, LDA',
  'Francometal, LDA',
];
